spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mariadb://localhost:3306/crazyspace
    username: crazyspace_local
    password: crazyspace_
    driver-class-name: org.mariadb.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: wkwjsrj5079@gmail.com
    password: cfwaiiclbuxpxzef
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

openai:
  api-key: "demo"

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
jwt:
  secret: 7a620a6cb951f5072105c91b9aec1a0399f3363712f729f04804f14379c07c5d5e70fdd28f807d3a4a2b59f23f7a0d9d28d91c924fafc7688426f8fdf1a5ed20
  expired: 3600000000L