### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "song",
  "email": "ㅂwkwjsrj5079@gmail.com",
  "password": "1ㅂㅈ234a",
  "phone": "010ㅂㅂ811111ㅈ011200",
  "birth": "0601"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "ssary00@naver.com",
  "password": "1234a"
}

### 실패 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"email": "ssary@naver.com",
"password": "1234a"
}

### ai생성
POST http://localhost:8080/api/generatedAiContents
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6InNzYXJ5MDBAbmF2ZXIuY29tIiwiaWF0IjoxNzIxNjU0NjAxLCJleHAiOjUzMjE2NTQ2MDF9.WHFgHUCWYJYl07VHz1AxVRhDtJrvcn0Z_9par-1KDwA

{
  "content": "한국어를 알려줘"
}
