### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "song",
  "email": "1234a@gmail.com",
  "password": "1234a",
  "phone": "811111ㅈ011200",
  "birth": "0601"
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "ssary00@naver.com",
  "password": "1234a"
}

### 실패 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"email": "ssary@naver.com",
"password": "1234a"
}

#### ai생성
#POST http://localhost:8080/api/generatedAiContents
#Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzc2FyeTAwQG5hdmVyLmNvbSIsImlhdCI6MTcyMjkyNDUzMiwiZXhwIjo1MzIyOTI0NTMyfQ.EBKZWjFDLDJk7cwgOeYmWsrQC2NVIJM0toRR8dR9NRQ
#
#{
#  "content": "네 역할이 머지?"
#}

### ai 대화
POST http://localhost:8080/api/conversations/1/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzc2FyeTAwQG5hdmVyLmNvbSIsImlhdCI6MTcyMjkyNDUzMiwiZXhwIjo1MzIyOTI0NTMyfQ.EBKZWjFDLDJk7cwgOeYmWsrQC2NVIJM0toRR8dR9NRQ

{
  "content": "네 역할이 머지?"
}

### ai대화 리스트
GET http://localhost:8080/api/conversations/1/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzc2FyeTAwQG5hdmVyLmNvbSIsImlhdCI6MTcyMjQ4NDkzNywiZXhwIjo1MzIyNDg0OTM3fQ.QKEVa8Z0SNKUxy7-flohymsEMdCJQ6vMc41ljXp2L1M
